controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /api

index:
    path: /
    controller: App\Controller\DefaultController::home
    defaults: {}

app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [POST]

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: [POST]

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: [GET]

app_mailer:
    path: /mailer
    controller: App\Controller\MailerController::sendEmail
    methods: [GET]

