controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /api

index:
    path: /index.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: /index.html
        permanent: true

app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [POST]

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: [POST]

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: [GET]