nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']   # Ou spécifiez des origines spécifiques, ex. ['http://localhost:3000']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    # Vous pouvez spécifier des règles CORS plus spécifiques pour certains chemins ou domaines
    paths:
        '^/api/':  # Appliquez CORS uniquement aux routes de l'API
            allow_origin: ['*']  # Ou spécifiez l'URL de votre frontend (ex. ['http://localhost:3000'])
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
