nelmio_cors:
    defaults:
        allow_origin: ['https://localhost:443']  # Remplacez par l'origine de votre frontend
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://localhost:443']  # Remplacez par l'origine de votre frontend
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: true  # Autorise l'envoi de cookies
